# syntax=docker/dockerfile:1

FROM golang:1.21

WORKDIR /learnadex

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

# build the learnadex binary
RUN go build -o bin/ ./cmd/learnadex

# expose the websocket port
EXPOSE 2112

ENTRYPOINT ["./bin/learnadex"]